Rebase feature/api_tests in feature/swagger
finderings/DualBoot pull request #17
Opened 2023-07-22 07:41 UTC by finderings

Добавил тесты на апи

2023-07-24 06:05 UTC, aleksandr-semenov-dbp requested changes

2023-07-24 06:05 UTC, aleksandr-semenov-dbp commented on test/test_tag.py
> +        data = self.filter({"title": "test"})
Здесь надо создать как минимум два объекта - один подходящий под фильтр и один не подходящий и убедится что фильтр вернул правильный

2023-07-24 06:05 UTC, aleksandr-semenov-dbp commented on test/test_tag.py
> +        assert len(data) == 2
Тесты написаны очень хорошо, но с некоторых пор мы внутри компании требуем чтобы они обязательно делились пустой строкой на три части - сетап, проверяемое действие и проверки, те:
```
   def test_list(self):
        second_tag = {"title": "new_test", }
        self.create(self.tag_attributes)
        self.create(second_tag)

        data = self.list()

        assert len(data) == 2
```

2023-07-24 10:25 UTC, finderings commented on test/test_tag.py
> +        data = self.filter({"title": "test"})
Сделал. В итоге во всех тестах вынес атрибуты второго объекта и создание первого объекта в начало, чтобы в каждом тесте не создавать их руками повторно

2023-07-24 10:25 UTC, finderings commented on test/test_tag.py
> +        assert len(data) == 2
Обновил во всех тестах. Я так понял, даже там где нет сетапа все равно надо делить уже на две части?

2023-07-26 04:21 UTC, aleksandr-semenov-dbp approved these changes

2023-07-26 07:26 UTC, merged