Rebase feature/models in develop
finderings/DualBoot pull request #8
Opened 2023-07-12 10:00 UTC by finderings

Создал модели task и tag

2023-07-17 04:12 UTC, aleksandr-semenov-dbp requested changes

2023-07-17 04:12 UTC, aleksandr-semenov-dbp commented on .gitignore
> +task_manager/__pycache__/wsgi.cpython-39.pyc
А зачем так? Не уследишь за каждым файлом, папками, как было раньше лучше

2023-07-17 09:41 UTC, finderings commented on .gitignore
> +task_manager/__pycache__/wsgi.cpython-39.pyc
Поправил

2023-07-18 05:22 UTC, aleksandr-semenov-dbp requested changes

2023-07-18 05:22 UTC, aleksandr-semenov-dbp commented on .gitignore
> +test/__pycache__/**
Нет, так тоже плохо, надо просто исключить эту папку везде одной строчкой/маской

2023-07-18 10:11 UTC, finderings commented on .gitignore
> +test/__pycache__/**
У меня одна из папок не игнорировалась с кэшем и я думал что делаю что-то не так, поэтому и были все эти ненужные строчки. Я разобрался в чем была проблема и теперь весь кэш нормально игнорируется одной строчкой

2023-07-20 04:21 UTC, aleksandr-semenov-dbp approved these changes

2023-07-26 07:35 UTC, merged